### ISSUE TITLE
Extracting weights from trained model

### ISSUE THREAD

**Issue by sachitkuhar** [apple/ml-quant#3]
Hello!

I trained ResNet18 on CIFAR100 dataset using ls-1 weights anf fp activations.
The weights saved are not quantized. How to quantize them?

Thanks!
<img width="468" alt="Screenshot 2020-08-17 at 6 48 47 PM" src="https://user-images.githubusercontent.com/27565537/90400577-50a8cc80-e0ba-11ea-9ffc-98fe5772fb7e.png">

**Comment by pouransari** [comment]
Hi Sachit,

The wights are always stored in FP (even when we use binary quantization). We need FP wights during training to gradually update weights using SGD. Storing FP weights allows us to resume the training.  In forward pass, however, only sign of the weights are used (together with the scalars). See [here](https://github.com/apple/ml-quant/blob/39197b5f54cd84ff35022c851dd2dcb753ca6b89/quant/binary/weight_quantization.py#L14) for the implementation detail. 

If you have trained a model, and would like to deploy it w/o carrying FP weights, you can convert weights to binary by applying [binary sign function](https://github.com/apple/ml-quant/blob/39197b5f54cd84ff35022c851dd2dcb753ca6b89/quant/binary/ste.py#L16) to them as a post-training step. Note that you should only apply this to weights that are supposed to be binary (for example, the first and last layers of the network are FP, and should not be converted to binary).

**Comment by sachitkuhar** [comment]
Thank you for your reply. This worked for me. 

Thanks!
